# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
parallel_matrix <- function(nthreads, nrow, ncol) {
    .Call('_manticore_tests_parallel_matrix', PACKAGE = 'manticore.tests', nthreads, nrow, ncol)
}

#' @export
parallel_runif <- function(nthreads, iterations, number) {
    .Call('_manticore_tests_parallel_runif', PACKAGE = 'manticore.tests', nthreads, iterations, number)
}

