on: [push, pull_request]

name: Run tests

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    container: rocker/r-base:latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Set directories
      run: |
        R --slave -e "cat(paste0('R_PKG_DIR=', .libPaths()[1]))" >> $GITHUB_ENV

    - name: Restore the package directory
      uses: actions/cache@v2
      with:
        path: ${{ env.R_PKG_DIR }}
        key: preinstalled-packages

    - name: Install dependencies
      shell: Rscript {0}
      run: |
        install.packages(c("Rcpp", "testthat"))

    - name: Install the test package
      run: R CMD INSTALL tests/R

    - name: Run the tests
      working-directory: tests/R/tests
      shell: Rscript {0}
      run: |
        testthat::test_file("testthat.R", stop_on_failure=TRUE)
      env:
        MANTICORE_TESTS_NTHREADS: 2
